name: CI

on:
  push:
    branches: [main dev dylan/shellcheck]
  pull_request:
    branches: [main dev]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2059 -e SC2034 -e SC1090
